# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nMApcz1blblrSTQQ5bSmKstyHIl8Lmn
"""

import random
import time
import matplotlib.pyplot as plt

# -----------------------------
# Insertion Sort
# -----------------------------
def insertion_sort(A):
    for j in range(1, len(A)):
        key = A[j]
        i = j - 1

        while i >= 0 and A[i] > key:
            A[i + 1] = A[i]
            i -= 1

        A[i + 1] = key


# -----------------------------
# Merge Sort
# -----------------------------
def merge(A, p, q, r):

    L = A[p:q+1]
    R = A[q+1:r+1]

    i = j = 0
    k = p

    while i < len(L) and j < len(R):

        if L[i] <= R[j]:
            A[k] = L[i]
            i += 1
        else:
            A[k] = R[j]
            j += 1

        k += 1

    while i < len(L):
        A[k] = L[i]
        i += 1
        k += 1

    while j < len(R):
        A[k] = R[j]
        j += 1
        k += 1


def merge_sort(A, p, r):

    if p < r:
        q = (p + r) // 2

        merge_sort(A, p, q)
        merge_sort(A, q + 1, r)

        merge(A, p, q, r)


# -----------------------------
# измерение времени
# -----------------------------
def measure(sort_func, arr, merge=False):

    start = time.perf_counter()

    if merge:
        sort_func(arr, 0, len(arr)-1)
    else:
        sort_func(arr)

    return time.perf_counter() - start


sizes = [1000, 5000, 10000, 50000]


def run_test(data_type):

    insertion_times = []
    merge_times = []

    for n in sizes:

        if data_type == "random":
            arr = [random.randint(0, n) for _ in range(n)]

        elif data_type == "sorted":
            arr = list(range(n))

        elif data_type == "reversed":
            arr = list(range(n, 0, -1))

        elif data_type == "nearly":
            arr = list(range(n))
            for _ in range(int(n * 0.05)):
                i = random.randint(0, n-1)
                j = random.randint(0, n-1)
                arr[i], arr[j] = arr[j], arr[i]

        arr1 = arr.copy()
        arr2 = arr.copy()

        insertion_times.append(measure(insertion_sort, arr1))
        merge_times.append(measure(merge_sort, arr2, True))

    return insertion_times, merge_times


# -----------------------------
# графики
# -----------------------------
tests = {
    "random": "График времени выполнения с рандомными данными",
    "sorted": "График времени выполнения с отсортированными данными",
    "reversed": "График времени выполнения с обратными данными",
    "nearly": "График времени выполнения с почти отсортированными данными"
}


for key, title in tests.items():

    ins, mer = run_test(key)

    plt.figure()

    plt.plot(sizes, ins, marker='o', label="Insertion Sort")
    plt.plot(sizes, mer, marker='s', label="Merge Sort")

    plt.xlabel("Размер массива (n)")
    plt.ylabel("Время выполнения (сек)")
    plt.title(title)

    plt.legend()
    plt.grid(True)

    plt.savefig(f"{key}.png")   # сохраняем картинку
    plt.show()

